codecov:
  notify:
    after_n_builds: 2

coverage:
  status:
    project:
      default: off
      unittest:
        flags: unittest
        target: 85%
flags:
  unittest:
    # only test unittests
    paths:
      - Tea/

ignore:
  - "TeaUnitTests/" # ignore TeaUnitTests
