name: unitTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.811
    - name: install altcover
      run: dotnet tool install --global altcover.visualizer
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test TeaUnitTests/ /p:AltCover=true
      env:
        CA: ${{ secrets.CA }}
    - name: CodeCov
      run: bash <(curl -s https://codecov.io/bash)
